USE [master]
GO

/****** Object:  Database [StudentPortal]    Script Date: 6/6/2020 8:51:32 PM ******/
CREATE DATABASE [StudentPortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StudentPortal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StudentPortal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StudentPortal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StudentPortal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudentPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudentPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudentPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudentPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudentPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudentPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudentPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StudentPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudentPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudentPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudentPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudentPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudentPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudentPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudentPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudentPortal] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StudentPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudentPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudentPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudentPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudentPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudentPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StudentPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudentPortal] SET RECOVERY FULL 
GO

ALTER DATABASE [StudentPortal] SET  MULTI_USER 
GO

ALTER DATABASE [StudentPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudentPortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudentPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudentPortal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StudentPortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudentPortal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StudentPortal] SET  READ_WRITE 
GO

